//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.11 at 10:15:06 PM CEST 
//


package com.bpel4mobile.internal.definition;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tDeadlines", propOrder = {
    "startDeadline",
    "completionDeadline"
})
public class Deadlines{

    protected List<TDeadline> startDeadline;
    
    protected List<TDeadline> completionDeadline;

    
    public List<TDeadline> getStartDeadline() {
        if (startDeadline == null) {
            startDeadline = new ArrayList<TDeadline>();
        }
        return this.startDeadline;
    }
   
    public List<TDeadline> getCompletionDeadline() {
        if (completionDeadline == null) {
            completionDeadline = new ArrayList<TDeadline>();
        }
        return this.completionDeadline;
    }

}
