//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.11 at 10:15:06 PM CEST 
//


package com.bpel4mobile.internal.definition;

import java.util.List;

import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;

import com.google.common.collect.Lists;

public class From {

    protected String logicalPeopleGroup;
    
    private List<Argument> arguments;

    @XmlAttribute(name = "logicalPeopleGroup")
    public String getLogicalPeopleGroup() {
        return logicalPeopleGroup;
    }

    public void setLogicalPeopleGroup(String value) {
        this.logicalPeopleGroup = value;
    }

    @XmlElement(name="argument", namespace=WS_HT_Namespace.URL)
	public List<Argument> getArguments() {
    	if(arguments == null){
    		arguments = Lists.newArrayList();
    	}
		return arguments;
	}

	public void setArguments(List<Argument> arguments) {
		this.arguments = arguments;
	}

}
