//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.11 at 10:15:06 PM CEST 
//


package com.bpel4mobile.internal.definition;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;


@XmlRootElement(name="humanInteractions", namespace=WS_HT_Namespace.URL)
public class HumanInteractions {

    protected LogicalPeopleGroups logicalPeopleGroups;
    
    protected Tasks tasks;

    @XmlElement(name="logicalPeopleGroups", namespace=WS_HT_Namespace.URL)
    public LogicalPeopleGroups getLogicalPeopleGroups() {
        return logicalPeopleGroups;
    }

    public void setLogicalPeopleGroups(LogicalPeopleGroups value) {
        this.logicalPeopleGroups = value;
    }

    @XmlElement(name="tasks", namespace=WS_HT_Namespace.URL)
    public Tasks getTasks() {
        return tasks;
    }

    public void setTasks(Tasks value) {
        this.tasks = value;
    
    }

}
